rvm: '2.5.0'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'CREATE TABLE messages (id SERIAL PRIMARY KEY, message VARCHAR(300), post_time TIMESTAMP, userid INT );' -U postgres
  - psql -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(60),
                         username VARCHAR(60) NOT NULL UNIQUE,
                         email VARCHAR(150) NOT NULL UNIQUE,
                         password VARCHAR(60) NOT NULL );' -U postgres
